"""Generated by BuildFlow."""

from buildflow import Flow
from buildflow.io.gcp import BigQueryDataset, BigQueryTable

from schemas import RequestSchema, TableSchema

# Define a BigQuery table to sink data into
bigquery_dataset = BigQueryDataset(
    dataset_name="collector_demo",
    project_id="tanke-dev-399703",
)
bigquery_table = BigQueryTable(
    dataset=bigquery_dataset,
    table_name="demo_table",
).options(schema=TableSchema)


# Create a new Flow instance
app = Flow()


# Optional Step: Enable infra state management for the BigQuery dataset and table
app.manage(bigquery_dataset, bigquery_table)


# Create an endpoint that will collect the data via HTTP and write to the BigQuery table
@app.collector("/", "POST", sink=bigquery_table)
def collect_data(request: RequestSchema) -> TableSchema:
    """Collect data from request."""
    return TableSchema(
        device_id=request.device_id,
        timestamp=request.timestamp,
        average_value=sum(request.values) / len(request.values),
    )
